### ISSUE TITLE
FEATURE - Include Account Name in Output Models

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_pinterest#16]
**Are you a Fivetran customer?** 

Fivetran created request

**Is your feature request related to a problem? Please describe.**
 
The account name is not included within these reports. This therefore means the account name is not included in the ad reporting model.

**Describe the solution you'd like**
 
Include the `account_name` in the source models and also flow into the `ad_adapter` model within Pinterest to then also be included in the ad reporting model.

**Describe alternatives you've considered**
 
No alternatives available currently.

**Comment by fivetran-joemarkiewicz** [comment]
@bnealdefero I wanted to tag you here as we had chatted a few weeks ago that you may be open to sharing a sample .csv file of the `advertiser_history`. Since our team does not have this data internally, it is pretty difficult to recreate the table structure with accuracy. As such, a sample .csv should help us integrate the account name information into this model and others downstream.

Let me know if this would be possible share 😄  Also, let me know if you believe the account information is somewhere other than `advertiser_history`. From my inspection of the ERD, that seems to be the table for this information but would love your insight on this as well. Thanks!

**Comment by bnealdefero** [comment]
Hi @fivetran-joemarkiewicz , shared a .csv file with you via slack. Let me know if you need any additional data to play with..

Thanks!

**Comment by fivetran-joemarkiewicz** [comment]
Thanks again for sharing the sample seed data with our team @bnealdefero 🙌 

Since then, I was able to open a few PRs that implement the `advertiser_history` fields into the final models. Let me know if you have a chance to test the working branches. Otherwise, the team will review the open PRs and integrate into the next releases.

> FYI both the Pinterest Ads and Ad Reporting working branches have are only compatible with dbt v1

The Pinterest Ads working branch:
```yml
packages:
  - git: https://github.com/fivetran/dbt_pinterest.git
    revision: feature/advertiser_addition
    warn-unpinned: false
```

The Ad Reporting working branch:
```yml
packages:
  - git: https://github.com/fivetran/dbt_ad_reporting.git
    revision: feature/pinterest_account_addition
    warn-unpinned: false
```
