### ISSUE TITLE
FEATURE - Include Account Information for Snapchat in the Ad_Reporting Model

### ISSUE THREAD

**Issue by csoule-shaker** [fivetran/dbt_pinterest#17]
**Are you a Fivetran customer?** 
Chris Soule, Data Architect InterWorks

**Is your feature request related to a problem? Please describe.**
The account name is not included within these reports. This therefore means the account name is not included in the ad reporting model.

**Describe the solution you'd like**
Include the Account Name and Account ID fields in the stg_snapchat_ads.sql model and the subsequent ad_reporting model. 

**Describe alternatives you've considered**
No alternatives available currently.

**Comment by fivetran-joemarkiewicz** [comment]
This feature has been integrated into the `dbt_ad_reporting` package via the above mentioned/merged PRs.

Closing this issue as it has since been addressed. Thanks again @csoule-shaker for opening this issue!
