### ISSUE TITLE
Research ability to add Passthrough Columns

### ISSUE THREAD

**Issue by fivetran-kristin** [fivetran/dbt_pinterest#8]
The `pin_promotion_report` table includes additional metrics (other than spend, impressions, and clicks) that will be helpful to include in the `pinterest_ads__ad_adapter` model.

Determine whether or not it is feasible to allow users to add in additional metrics that will then be aggregated in the final model.

I've started testing out this functionality in the [`passthrough_variable` branch](https://github.com/fivetran/dbt_pinterest/tree/passthrough_variable).

**Comment by fivetran-kristin** [comment]
Before we do this, one thing we'll need to do some discovery on is:
- What are some example set of columns customers have in the `pin_promotion_report` table
- How will this impact the ad_reporting roll up package that is set to release shortly

**Comment by arniwesth** [comment]
Thanks for looking into this possibility. In my particular case, I need to extract checkout conversions from `pin_promotion_report`.
These are the relevant fields: 
```
total_checkout_desktop_action_to_desktop_conversion
total_checkout_desktop_action_to_mobile_conversion
total_checkout_desktop_action_to_mobile_conversion
total_checkout_mobile_action_to_desktop_conversion
total_checkout_mobile_action_to_mobile_conversion
total_checkout_tablet_action_to_desktop_conversion
total_checkout_tablet_action_to_mobile_conversion
total_checkout_tablet_action_to_tablet_conversion
```

**Comment by fivetran-kristin** [comment]
Hey @arniwesth - we're evaluating whether to add this to our next sprint. I'm curious, is this still a priority for you, or have you found a workaround?

**Comment by arniwesth** [comment]
Hey @fivetran-kristin - I found a workaround where we can still utilize the Fivetran dbt package and add custom metrics as we need. So not a high priority from our perspective.

**Comment by fivetran-joemarkiewicz** [comment]
Closing this Issue as the previously mentioned PRs have been merged.
